//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        public int ID { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string ChucDanh { get; set; }
        public string MaPB { get; set; }
        public string TenPB { get; set; }
        public string BoPhan { get; set; }
        public string LoaiCa { get; set; }
        public string Ca { get; set; }
        public string NoiLam { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string MaCH { get; set; }
        public string TenCH { get; set; }
        public string NhanCa { get; set; }
        public string DoiCa { get; set; }
        public string Loai { get; set; }
        public string LoaiNghi { get; set; }
        public string LyDoNghi { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public string LoaiCong { get; set; }
        public int SoGioNghi { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string TrangThaiDuyet { get; set; }
        public Nullable<System.DateTime> NgayLamLai { get; set; }
    }
}
