//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.BoSuuTaps = new HashSet<BoSuuTap>();
        }
    
        public string ID { get; set; }
        public string Ten { get; set; }
        public string GroupCat { get; set; }
        public string Func { get; set; }
        public string RR { get; set; }
        public string Brand { get; set; }
        public string NguonNhap { get; set; }
        public Nullable<int> SLCombo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoSuuTap> BoSuuTaps { get; set; }
    }
}
