//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTHUCTAPEntities1 : DbContext
    {
        public DBTHUCTAPEntities1()
            : base("name=DBTHUCTAPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BD> BDS { get; set; }
        public virtual DbSet<BoSuuTap> BoSuuTaps { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CHUSOHUU> CHUSOHUUs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_BBM_SMART_HRM> tbl_BBM_SMART_HRM { get; set; }
        public virtual DbSet<tbl_Bill> tbl_Bill { get; set; }
        public virtual DbSet<CaLamViec> CaLamViecs { get; set; }
        public virtual DbSet<tbl_BBS_Collection> tbl_BBS_Collection { get; set; }
        public virtual DbSet<tbl_bbs_collection_detail> tbl_bbs_collection_detail { get; set; }
        public virtual DbSet<tbl_bbs_out_ar_auto> tbl_bbs_out_ar_auto { get; set; }
        public virtual DbSet<tbl_moTaCongViec> tbl_moTaCongViec { get; set; }
        public virtual DbSet<tbl_potong> tbl_potong { get; set; }
        public virtual DbSet<tbl_tmp> tbl_tmp { get; set; }
    }
}
