//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductAllTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tại Ngân hàng.
        /// </summary>
        public static string atBank {
            get {
                return ResourceManager.GetString("atBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string bankAccount {
            get {
                return ResourceManager.GetString("bankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sâu.
        /// </summary>
        public static string boxHeight {
            get {
                return ResourceManager.GetString("boxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cổng.
        /// </summary>
        public static string boxHome_1 {
            get {
                return ResourceManager.GetString("boxHome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kết nối.
        /// </summary>
        public static string boxHome_2 {
            get {
                return ResourceManager.GetString("boxHome_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác.
        /// </summary>
        public static string boxHome_3 {
            get {
                return ResourceManager.GetString("boxHome_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cao.
        /// </summary>
        public static string boxLength {
            get {
                return ResourceManager.GetString("boxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước thùng/hộp.
        /// </summary>
        public static string boxSize {
            get {
                return ResourceManager.GetString("boxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rộng.
        /// </summary>
        public static string boxWidth {
            get {
                return ResourceManager.GetString("boxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string btEdit {
            get {
                return ResourceManager.GetString("btEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hình doanh nghiệp.
        /// </summary>
        public static string businessType {
            get {
                return ResourceManager.GetString("businessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hàng.
        /// </summary>
        public static string categoryCode {
            get {
                return ResourceManager.GetString("categoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lợi thế của DN.
        /// </summary>
        public static string competencyCore {
            get {
                return ResourceManager.GetString("competencyCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người liên hệ.
        /// </summary>
        public static string contactEmail {
            get {
                return ResourceManager.GetString("contactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người liên hệ.
        /// </summary>
        public static string contactName {
            get {
                return ResourceManager.GetString("contactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ĐT người liên hệ.
        /// </summary>
        public static string contactPhone {
            get {
                return ResourceManager.GetString("contactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string contactPosition {
            get {
                return ResourceManager.GetString("contactPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức hợp tác.
        /// </summary>
        public static string cooperateType {
            get {
                return ResourceManager.GetString("cooperateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ phủ thị trường.
        /// </summary>
        public static string coverageMarket {
            get {
                return ResourceManager.GetString("coverageMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng chính.
        /// </summary>
        public static string customerKey {
            get {
                return ResourceManager.GetString("customerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước sản phẩm.
        /// </summary>
        public static string dimension {
            get {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sâu.
        /// </summary>
        public static string dimensionHeight {
            get {
                return ResourceManager.GetString("dimensionHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cao.
        /// </summary>
        public static string dimensionLength {
            get {
                return ResourceManager.GetString("dimensionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rộng.
        /// </summary>
        public static string dimensionWidth {
            get {
                return ResourceManager.GetString("dimensionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiếu khấu thương mại.
        /// </summary>
        public static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngành hàng.
        /// </summary>
        public static string divisionCode {
            get {
                return ResourceManager.GetString("divisionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn điện tử.
        /// </summary>
        public static string E_Invoice {
            get {
                return ResourceManager.GetString("E_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhân sự.
        /// </summary>
        public static string employeesScale {
            get {
                return ResourceManager.GetString("employeesScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP đang sử dụng.
        /// </summary>
        public static string ERP_Name {
            get {
                return ResourceManager.GetString("ERP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng M2F.
        /// </summary>
        public static string faceAcreage_total {
            get {
                return ResourceManager.GetString("faceAcreage_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số mặt trưng bày (CH).
        /// </summary>
        public static string faceQty {
            get {
                return ResourceManager.GetString("faceQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên doanh nghiệp.
        /// </summary>
        public static string firmName {
            get {
                return ResourceManager.GetString("firmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm công dụng.
        /// </summary>
        public static string functionCode {
            get {
                return ResourceManager.GetString("functionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm sản phẩm.
        /// </summary>
        public static string groupCode {
            get {
                return ResourceManager.GetString("groupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Guarantee.
        /// </summary>
        public static string guaranteeMinimum {
            get {
                return ResourceManager.GetString("guaranteeMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh sản phẩm.
        /// </summary>
        public static string imgLink {
            get {
                return ResourceManager.GetString("imgLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực hoạt động.
        /// </summary>
        public static string industryType {
            get {
                return ResourceManager.GetString("industryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ảnh sản phẩm.
        /// </summary>
        public static string lb_ImgUpload {
            get {
                return ResourceManager.GetString("lb_ImgUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload ảnh.
        /// </summary>
        public static string lb_ImgUpload2 {
            get {
                return ResourceManager.GetString("lb_ImgUpload2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cửa hàng phủ hàng.
        /// </summary>
        public static string listingQty {
            get {
                return ResourceManager.GetString("listingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất xứ.
        /// </summary>
        public static string manufactureCode {
            get {
                return ResourceManager.GetString("manufactureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí marketing.
        /// </summary>
        public static string marketingCost {
            get {
                return ResourceManager.GetString("marketingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL tối thiểu/lần giao tại CH.
        /// </summary>
        public static string MOQ {
            get {
                return ResourceManager.GetString("MOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Chọn trong danh sách -.
        /// </summary>
        public static string multi_def {
            get {
                return ResourceManager.GetString("multi_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí vận hành.
        /// </summary>
        public static string operatingCost {
            get {
                return ResourceManager.GetString("operatingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        public static string passwordRetrieval {
            get {
                return ResourceManager.GetString("passwordRetrieval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string phoneNo {
            get {
                return ResourceManager.GetString("phoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string placeHolderCM {
            get {
                return ResourceManager.GetString("placeHolderCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quảng cáo, khuyến mại....
        /// </summary>
        public static string PlaceholderMaketing {
            get {
                return ResourceManager.GetString("PlaceholderMaketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đặt hàng tối thiểu.
        /// </summary>
        public static string placeholderMOQ {
            get {
                return ResourceManager.GetString("placeholderMOQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thưởng/SP cho NVBH.
        /// </summary>
        public static string PlaceholderProductBonus {
            get {
                return ResourceManager.GetString("PlaceholderProductBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lợi nhuận tối thiểu vàgt;= Minimum Guarantee.
        /// </summary>
        public static string PlaceholderTradeDiscounts {
            get {
                return ResourceManager.GetString("PlaceholderTradeDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho bãi, vận chuyển....
        /// </summary>
        public static string PlaceholderWarehouse {
            get {
                return ResourceManager.GetString("PlaceholderWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới sản phẩm.
        /// </summary>
        public static string prdAdd {
            get {
                return ResourceManager.GetString("prdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không có tên, không lưu lại sản phẩm này?.
        /// </summary>
        public static string prdNoName {
            get {
                return ResourceManager.GetString("prdNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu năm trước.
        /// </summary>
        public static string previousRevenue {
            get {
                return ResourceManager.GetString("previousRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang trước.
        /// </summary>
        public static string prevPage {
            get {
                return ResourceManager.GetString("prevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOQ tại cửa hàng.
        /// </summary>
        public static string priceCost {
            get {
                return ResourceManager.GetString("priceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOQ tại kho HN/HCM.
        /// </summary>
        public static string priceCost1 {
            get {
                return ResourceManager.GetString("priceCost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán NET (+VAT).
        /// </summary>
        public static string priceRetail {
            get {
                return ResourceManager.GetString("priceRetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN HÀNG HÓA - DỊCH VỤ.
        /// </summary>
        public static string ProductInfoF1 {
            get {
                return ResourceManager.GetString("ProductInfoF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN ĐẶT HÀNG.
        /// </summary>
        public static string ProductInfoF2 {
            get {
                return ResourceManager.GetString("ProductInfoF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN HÀNG HÓA - DỊCH VỤ.
        /// </summary>
        public static string ProductInfoTT {
            get {
                return ResourceManager.GetString("ProductInfoTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy cách đóng gói.
        /// </summary>
        public static string QtyBox {
            get {
                return ResourceManager.GetString("QtyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho hiện có.
        /// </summary>
        public static string realityInventories {
            get {
                return ResourceManager.GetString("realityInventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ĐKKD.
        /// </summary>
        public static string registrationBusiness {
            get {
                return ResourceManager.GetString("registrationBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string registrationTax {
            get {
                return ResourceManager.GetString("registrationTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người đại diện.
        /// </summary>
        public static string representativeEmail {
            get {
                return ResourceManager.GetString("representativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện.
        /// </summary>
        public static string representativeName {
            get {
                return ResourceManager.GetString("representativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ĐT người đại diện.
        /// </summary>
        public static string representativePhone {
            get {
                return ResourceManager.GetString("representativePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string representativePosition {
            get {
                return ResourceManager.GetString("representativePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí bán hàng.
        /// </summary>
        public static string salesCost {
            get {
                return ResourceManager.GetString("salesCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và đóng.
        /// </summary>
        public static string Save_close {
            get {
                return ResourceManager.GetString("Save&close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục.
        /// </summary>
        public static string Save_Con {
            get {
                return ResourceManager.GetString("Save&Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string textchangePass {
            get {
                return ResourceManager.GetString("textchangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string textEnterNewPassword {
            get {
                return ResourceManager.GetString("textEnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUÊN MẬT KHẨU?.
        /// </summary>
        public static string textforgot_1 {
            get {
                return ResourceManager.GetString("textforgot_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy điền tên tài khoản và địa chỉ email để đặt lại mật khẩu!.
        /// </summary>
        public static string textforgot_2 {
            get {
                return ResourceManager.GetString("textforgot_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string textforgot_3 {
            get {
                return ResourceManager.GetString("textforgot_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email.
        /// </summary>
        public static string textforgot_4 {
            get {
                return ResourceManager.GetString("textforgot_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        public static string textforgot_5 {
            get {
                return ResourceManager.GetString("textforgot_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viet Eco là hệ sinh thái kết nối các nguồn lực hiện có trong xã hội, với mục tiêu.
        /// </summary>
        public static string textHome_1 {
            get {
                return ResourceManager.GetString("textHome_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        public static string textHome_10 {
            get {
                return ResourceManager.GetString("textHome_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiên cứu nhu cầu, phát triển các sản phẩm và dịch vụ tốt nhất, dựa trên lợi thế sẵn có của các bên.
        /// </summary>
        public static string textHome_2 {
            get {
                return ResourceManager.GetString("textHome_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đường đi ngắn nhất từ người có, đến đúng người cần, đúng thời điểm, với chi phí thấp nhất.
        /// </summary>
        public static string textHome_3 {
            get {
                return ResourceManager.GetString("textHome_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mang lại lợi ích tốt nhất cho Khách hàng và các thành viên của hệ sinh thái.
        /// </summary>
        public static string textHome_4 {
            get {
                return ResourceManager.GetString("textHome_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lực và hỗ trợ các thành viên phát triển bền vững, nâng vị thế của các thương hiệu Việt.
        /// </summary>
        public static string textHome_5 {
            get {
                return ResourceManager.GetString("textHome_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string textHome_6 {
            get {
                return ResourceManager.GetString("textHome_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về VietEco.
        /// </summary>
        public static string textHome_7 {
            get {
                return ResourceManager.GetString("textHome_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ hội hợp tác.
        /// </summary>
        public static string textHome_8 {
            get {
                return ResourceManager.GetString("textHome_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mạng lưới.
        /// </summary>
        public static string textHome_9 {
            get {
                return ResourceManager.GetString("textHome_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đăng nhập.
        /// </summary>
        public static string textlogin_1 {
            get {
                return ResourceManager.GetString("textlogin_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string textlogin_2 {
            get {
                return ResourceManager.GetString("textlogin_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string textlogin_3 {
            get {
                return ResourceManager.GetString("textlogin_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        public static string textlogin_4 {
            get {
                return ResourceManager.GetString("textlogin_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn đăng xuất?.
        /// </summary>
        public static string textlogout_1 {
            get {
                return ResourceManager.GetString("textlogout_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string textlogout_2 {
            get {
                return ResourceManager.GetString("textlogout_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string textlogout_3 {
            get {
                return ResourceManager.GetString("textlogout_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string textNewPassword {
            get {
                return ResourceManager.GetString("textNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string textoldPassword {
            get {
                return ResourceManager.GetString("textoldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trân trọng cảm ơn Quý đối tác đã gửi chào hàng sản phẩm mới!.
        /// </summary>
        public static string textpopup_1 {
            get {
                return ResourceManager.GetString("textpopup_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ sớm phản hồi thông tin và rất mong được hợp tác cùng quý vị..
        /// </summary>
        public static string textpopup_2 {
            get {
                return ResourceManager.GetString("textpopup_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string textpopup_3 {
            get {
                return ResourceManager.GetString("textpopup_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐIỀU KHOẢN HỢP TÁC (tiếp) và QUY ĐỊNH ĐỔI TRẢ.
        /// </summary>
        public static string textterm_1 {
            get {
                return ResourceManager.GetString("textterm_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string textterm_10 {
            get {
                return ResourceManager.GetString("textterm_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi xác nhận đã đọc, hiểu và đồng ý với điều khoản hợp tác và quy định đổi trả hàng hóa nêu trên..
        /// </summary>
        public static string textterm_2 {
            get {
                return ResourceManager.GetString("textterm_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty cần báo trước.
        /// </summary>
        public static string textterm_3 {
            get {
                return ResourceManager.GetString("textterm_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tháng kể từ thời điểm hết date để chúng tôi đổi cho Công ty sản phẩm mới tương đương date xa hơn..
        /// </summary>
        public static string textterm_4 {
            get {
                return ResourceManager.GetString("textterm_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và đóng.
        /// </summary>
        public static string textterm_5 {
            get {
                return ResourceManager.GetString("textterm_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string textterm_6 {
            get {
                return ResourceManager.GetString("textterm_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2F/CH.
        /// </summary>
        public static string textterm_7 {
            get {
                return ResourceManager.GetString("textterm_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG/CH.
        /// </summary>
        public static string textterm_8 {
            get {
                return ResourceManager.GetString("textterm_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ kho xuất.
        /// </summary>
        public static string textterm_9 {
            get {
                return ResourceManager.GetString("textterm_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XÂY DỰNG PHƯƠNG ÁN KINH DOANH.
        /// </summary>
        public static string TradingtermTT {
            get {
                return ResourceManager.GetString("TradingtermTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng xe vận tải.
        /// </summary>
        public static string truckQuantity {
            get {
                return ResourceManager.GetString("truckQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string UoM {
            get {
                return ResourceManager.GetString("UoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL/mô tả sản phẩm.
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế suất VAT (%).
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CƠ BẢN.
        /// </summary>
        public static string VendorInfoF1 {
            get {
                return ResourceManager.GetString("VendorInfoF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NĂNG LỰC HOẠT ĐỘNG.
        /// </summary>
        public static string VendorInfoF2 {
            get {
                return ResourceManager.GetString("VendorInfoF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN LIÊN HỆ.
        /// </summary>
        public static string VendorInfoF3 {
            get {
                return ResourceManager.GetString("VendorInfoF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN DOANH NGHIỆP.
        /// </summary>
        public static string VendorInfoTT {
            get {
                return ResourceManager.GetString("VendorInfoTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số M2 kho/xưởng.
        /// </summary>
        public static string warehouseAcreage {
            get {
                return ResourceManager.GetString("warehouseAcreage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ kho xuất.
        /// </summary>
        public static string warehouseDeparture {
            get {
                return ResourceManager.GetString("warehouseDeparture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng (gram).
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hoạt động.
        /// </summary>
        public static string yearActive {
            get {
                return ResourceManager.GetString("yearActive", resourceCulture);
            }
        }
    }
}
