//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bbs_out_ar_auto
    {
        public int ID { get; set; }
        public string KhoChiaCode { get; set; }
        public string KhoChiaName { get; set; }
        public string TinhKhoChia { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> CH_TSF { get; set; }
        public string Mien { get; set; }
        public string Tinh { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> PS_ERP { get; set; }
        public Nullable<decimal> DS_ERP { get; set; }
        public Nullable<decimal> Min_PSF { get; set; }
        public Nullable<decimal> SLTon { get; set; }
        public Nullable<decimal> SLBanD30 { get; set; }
        public Nullable<decimal> StockDay { get; set; }
        public Nullable<decimal> SLGoiY { get; set; }
        public Nullable<decimal> SLDeXuat { get; set; }
        public Nullable<decimal> SLDuyet { get; set; }
        public Nullable<decimal> RNtopsalefunct { get; set; }
        public string asRegion { get; set; }
        public string Status { get; set; }
        public string StatusERP { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> Type { get; set; }
        public string Step { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Aprovedate { get; set; }
        public string Approveby { get; set; }
        public string LyDo { get; set; }
    }
}
