//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_potong
    {
        public string Function { get; set; }
        public string FFunction { get; set; }
        public string MuaVu { get; set; }
        public string hisdate { get; set; }
        public string POTongMienBac { get; set; }
        public string POTongMienNam { get; set; }
        public string POTongMienBacInt { get; set; }
        public string POTongMienNamInt { get; set; }
        public string POTongToanQuoc { get; set; }
        public string POTongToanQuocInt { get; set; }
        public string GiaTriPOTongToanQuoc { get; set; }
        public string POQuahan { get; set; }
        public string TonKho { get; set; }
        public string Intransit { get; set; }
        public string POTongCR { get; set; }
        public string DatThem { get; set; }
        public string NgayTonKho { get; set; }
        public string sumPOTongMienBac { get; set; }
        public string sumPOTongMienNam { get; set; }
        public string sumPOTongToanQuoc { get; set; }
        public string sumGiaTriPOTongToanQuoc { get; set; }
        public string sumTonKho { get; set; }
        public string sumIntransit { get; set; }
        public string sumPOTongCR { get; set; }
        public string sumDatThem { get; set; }
    }
}
