//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bbs_collection_detail
    {
        public int ID { get; set; }
        public string IDparent { get; set; }
        public string catcode { get; set; }
        public string catname { get; set; }
        public string groupcode { get; set; }
        public string groupname { get; set; }
        public string functcode { get; set; }
        public string functname { get; set; }
        public string Range { get; set; }
        public string brandcode { get; set; }
        public string brandname { get; set; }
        public string nguonnhapcode { get; set; }
        public string nguonnhapname { get; set; }
        public string MuaVu { get; set; }
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string imglink { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> slcombo { get; set; }
        public Nullable<int> status { get; set; }
        public string step { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> aprovedate { get; set; }
        public string aproveby { get; set; }
        public string aprovenote { get; set; }
        public Nullable<int> SLTon { get; set; }
    }
}
