//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BBM_SMART_HRM
    {
        public int ID { get; set; }
        public string KhoiCode { get; set; }
        public string KhoiName { get; set; }
        public string BoPhanCode { get; set; }
        public string BoPhanName { get; set; }
        public string PhongBanCode { get; set; }
        public string PhongBanName { get; set; }
        public string CapBac { get; set; }
        public string ChucDanh { get; set; }
        public string MaCongViec { get; set; }
        public string TenCongViec { get; set; }
        public Nullable<int> TanSuatThucHien { get; set; }
        public Nullable<decimal> ThoiLuongThucHien { get; set; }
        public Nullable<decimal> TongThoiLuongThucHien { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string TinhTrangHD { get; set; }
    }
}
