//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BBS_Collection
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string MuaVu { get; set; }
        public string DoiTuong { get; set; }
        public string GioiTinh { get; set; }
        public string ThuNhap { get; set; }
        public string USP { get; set; }
        public string ThongDiep { get; set; }
        public string Themelink { get; set; }
        public Nullable<int> Status { get; set; }
        public string step { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Aprovedate { get; set; }
        public string AproveBy { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Aprovedate1 { get; set; }
        public string Aprovedate2 { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
