//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductAllTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_moTaCongViec
    {
        public int MaCV { get; set; }
        public string TenCV { get; set; }
        public Nullable<decimal> TanSuatCongViec { get; set; }
        public Nullable<decimal> ThoiLuongThucHien { get; set; }
        public string Khoi { get; set; }
        public string PhongBan { get; set; }
        public string BoPhan { get; set; }
        public string CapBac { get; set; }
        public string ChucDanh { get; set; }
        public string MaNv { get; set; }
        public string TenNv { get; set; }
        public string TinhTrangHoatDong { get; set; }
        public string Mien { get; set; }
        public string MaCHBP { get; set; }
        public string TenCHBP { get; set; }
        public Nullable<decimal> TongThoiGian { get; set; }
    }
}
